os:
  - linux
language: cpp
compiler:
  - clang
jdk:
  - oraclejdk8
go:
  - 1.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y realpath docker.io
  - go env
  - echo ${GOROOT}
  - jdk_switcher use oraclejdk8
  - wget http://dl.google.com/android/android-sdk_r23-linux.tgz
  - tar xvf android-sdk_r23-linux.tgz
  - export PATH=${PATH}:${PWD}/android-sdk-linux/tools:${PWD}/android-sdk-linux/platform-tools
  - ./download_bazel.sh /tmp/
  - export PATH=${PATH}:/tmp/bazel/output
  - ./setup_bazel.sh
  - echo "sdk.dir=${PWD}/android-sdk-linux" > local.properties
  - ( while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui --filter platform-tool,tool
script:
  - bazel build //...
  - bazel test --test_output=errors //...
  - ./bazel-bin/shipshape/cli/shipshape --tag=local --logtostderr .
