os:
  - linux
language: cpp
compiler:
  - clang
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y realpath
  - wget https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
  - tar zxf go1.4.2.linux-amd64.tar.gz
  - export PATH=${PATH}:${PWD}/go/bin
  - export GOROOT=${PWD}/go
  - jdk_switcher use oraclejdk8
  - wget http://dl.google.com/android/android-sdk_r23-linux.tgz
  - tar xvf android-sdk_r23-linux.tgz
  - export PATH=${PATH}:${PWD}/android-sdk-linux/tools:${PWD}/android-sdk-linux/platform-tools
  - ./download_bazel.sh ${PWD}
  - export PATH=${PATH}:${PWD}/bazel/output
  - ./setup_bazel.sh
  - echo "sdk.dir=${PWD}/android-sdk-linux" > local.properties
  - echo "y" | android update sdk --no-ui --filter platform-tools,tools
script:
  - bazel test //shipshape/...
